name: Run job on JLSE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 'jlse-run/*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, jlse]

    # Steps represent a sequence of tasks that will be executed as part of the job
    defaults:
      run:
        working-directory: run/automake
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Setup dependencies
      run: |
        pip install ../../
        pip install pytest mock
        cd ../../qtree && pip install .

    - name: Checks
      run: |
          echo $PATH
          pwd
          /usr/bin/whoami

    - name: Run run/automake/run.sh
      run: ./run.sh
      	
    - name: Commit results
      uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      with:
        add: 'results'
        author_name: Actions Runner
        author_email: mail@example.com
        message: 'jlse-results for `$(git show -s --format=%s)`'
