# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
    paths-ignore: [ 'docs/**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: robbyjo/ubuntu-mkl:18.04-2019.1

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Setup git
      run: |
        yes | apt-get update
        yes | apt-get install software-properties-common
        yes | add-apt-repository ppa:git-core/ppa
        yes | apt-get update
        yes | apt-get install git

    - uses: actions/checkout@v2
      with:
        submodules: recursive

      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Link to proper python
      run: |
        which pip; which pip3
        ln -srf $(which python3) /usr/bin/python
        ln -srf $(which pip3) /usr/bin/pip
        which pip; which pip3
        echo $PATH
        
        
    - name: Setup dependencies
      run: |
        /usr/bin/env pip install .
        /usr/bin/env pip install pytest mock
        (cd qtree && /usr/bin/env pip install .)
        (cd scratchpad/cpp_connections/vanilia/nparray/ && /usr/bin/env pip install .)
  
    - name: Test
      run: cd qtensor && pytest
