# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
    paths-ignore: [ 'docs/**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: robbyjo/ubuntu-mkl:18.04-2019.1

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Setup git
      run: |
        apt-get install software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update
        apt-get install git


    - uses: actions/checkout@v2
      with:
          submodules: recursive
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
        
    - name: Setup dependencies
      run: |
        pip install .
        pip install pytest mock
        (cd qtree && pip install .)
        (cd scratchpad/cpp_connections/vanilia/nparray/ && pip install .)
  
    - name: Test
      run: cd qtensor && pytest
